# Generated by Django 4.2.30 on 2026-04-29 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=120)),
                ('session_id', models.CharField(max_length=120)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('add_to_cart', 'Add To Cart'), ('remove_from_cart', 'Remove From Cart'), ('checkout_started', 'Checkout Started'), ('checkout_abandoned', 'Checkout Abandoned'), ('purchase_completed', 'Purchase Completed'), ('form_submitted', 'Form Submitted'), ('scroll_depth', 'Scroll Depth'), ('button_clicked', 'Button Clicked'), ('repeat_visit', 'Repeat Visit'), ('custom', 'Custom')], max_length=40)),
                ('url', models.URLField(blank=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='companies.company')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='leads.lead')),
                ('visitor_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='leads.visitorsession')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'created_at'], name='events_even_company_2d9e20_idx'), models.Index(fields=['company', 'event_type'], name='events_even_company_f7bc32_idx'), models.Index(fields=['company', 'visitor_id'], name='events_even_company_2a3844_idx'), models.Index(fields=['company', 'session_id'], name='events_even_company_f81b69_idx')],
            },
        ),
    ]
