# Generated by Django 4.2.30 on 2026-04-29 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('trigger_type', models.CharField(choices=[('event_based', 'Event Based'), ('score_based', 'Score Based'), ('time_based', 'Time Based')], max_length=40)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('cooldown_minutes', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='executed', max_length=30)),
                ('trigger_event_id', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('automation_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automations.automationrule')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_executions', to='companies.company')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_executions', to='leads.lead')),
            ],
        ),
        migrations.AddIndex(
            model_name='automationrule',
            index=models.Index(fields=['company', 'trigger_type', 'is_active'], name='automations_company_120846_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['company', 'executed_at'], name='automations_company_ce59fa_idx'),
        ),
    ]
