# Generated by Django 4.2.30 on 2026-04-29 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('name', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(default='new', max_length=40)),
                ('intent_score', models.IntegerField(default=0)),
                ('intent_category', models.CharField(choices=[('cold_visitor', 'Cold Visitor'), ('warm_lead', 'Warm Lead'), ('hot_lead', 'Hot Lead'), ('customer', 'Customer'), ('at_risk_customer', 'At Risk Customer')], default='cold_visitor', max_length=40)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('total_product_views', models.PositiveIntegerField(default=0)),
                ('total_cart_adds', models.PositiveIntegerField(default=0)),
                ('total_checkout_attempts', models.PositiveIntegerField(default=0)),
                ('total_purchases', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=120)),
                ('session_id', models.CharField(max_length=120)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('device', models.CharField(blank=True, max_length=80)),
                ('browser', models.CharField(blank=True, max_length=80)),
                ('referrer', models.URLField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_sessions', to='companies.company')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='leads.lead')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'visitor_id'], name='leads_visit_company_aeabb9_idx'), models.Index(fields=['company', 'session_id'], name='leads_visit_company_4287c0_idx')],
                'unique_together': {('company', 'session_id')},
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'visitor_id'], name='leads_lead_company_b43d49_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'intent_category'], name='leads_lead_company_e145ff_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'intent_score'], name='leads_lead_company_25c7be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('company', 'visitor_id')},
        ),
    ]
