# Generated by Django 4.2.30 on 2026-04-29 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('confidence_score', models.FloatField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'created_at'], name='ai_engine_a_company_4e2c35_idx'), models.Index(fields=['company', 'insight_type'], name='ai_engine_a_company_267742_idx')],
            },
        ),
    ]
